# -*- coding: utf-8 -*-
"""Propaganda_ideology_setting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19G4-wZK6lFOONsVF-_cYoYX9RNyclFiU
"""

import pandas as pd
import nltk
from nltk.corpus import PlaintextCorpusReader
import os

nltk.download('punkt')

from google.colab import drive
drive.mount('/content/drive')

base = '/content/drive/MyDrive/Scraped_Sputnik_FULL'

folders = {
    "Corpus_1": f"{base}/Corpus_1",
    "Corpus_2": f"{base}/Corpus_2",
    "Corpus_3": f"{base}/Corpus_3"
}


#framing ideology keywords
ideology = { "membership": ["ingroup", "outgroup", "identity", "belonging", "community"],
                     "activities": ["action", "behavior", "movement", "campaign", "resistance", "tradition"],
                      "aims": ["goal", "aim", "agenda", "purpose", "mission", "objective"],
                      "norms": ["good", "bad", "moral", "ethical", "justice", "freedom", "equality", "truth"],
                      "relations": ["power", "dominance", "authority", "oppression", "conflict", "hierarchy"],
                      "resources": ["resources", "wealth", "rights", "privilege", "inequality", "distribution"] }

articles, ids, corpora = zip(*[
    (" ".join(PlaintextCorpusReader(path, '.*').words(fid)).lower(), fid, name)
    for name, path in folders.items()
    for fid in PlaintextCorpusReader(path, '.*').fileids()
])

#assigning ideology frame to each article
all_articles = [
    {
        "corpus": corpus,
        "article_id": fid,
        "frame": (
            "unassigned" if max((sum(article.count(k) for k in keywords) for keywords in ideology.values())) == 0
            else max(ideology, key=lambda f: sum(article.count(k) for k in ideology[f]))
        ),
        "keyword_count": max((sum(article.count(k) for k in keywords) for keywords in ideology.values()))
    }
    for article, fid, corpus in zip(articles, ids, corpora)
]


df_articles = pd.DataFrame(all_articles)

df_articles.to_csv("/content/drive/MyDrive/Sputnik_Ideology.csv", index=False)
print("\nArticles saved.")

df_articles['analysis_type'] = "ideology"

import matplotlib.pyplot as plt
import seaborn as sns

heatmap = df_articles.pivot_table(index='frame', columns='analysis_type', aggfunc='size', fill_value=0)
plt.figure(figsize=(10,6))
sns.heatmap(heatmap, annot=True, fmt='d', cmap='Spectral')
plt.show()

#looping through each corpus
for corpus_name in df_articles['corpus'].unique():
    df_corpus = df_articles[df_articles['corpus'] == corpus_name]

    heatmap = df_corpus.pivot_table(
        index='frame',
        columns='analysis_type',
        aggfunc='size',
        fill_value=0
    )

    plt.figure(figsize=(10,6))
    sns.heatmap(heatmap, annot=True, fmt='d', cmap='Spectral')
    plt.title(f"Frame Counts Heatmap - {corpus_name}")
    plt.show()